Добавление функция сжатия изображения для экономии места
Studio-Yandex-Practicum/bot_delo_zhivet pull request #130
Opened 2023-04-18 20:10 UTC by CodeDemonTony

1) Добавлена функция сжатия изображения в src/bot/service/pollution.py
2) Импорт функции сжатия и ее использование в src/bot/handlers/pollution.py

2023-04-19 10:25 UTC, Raidzin commented
Думаю не стоит удалять `.env.example` (надо бы его вернуть)

2023-04-19 21:11 UTC, Raidzin commented on src/bot/service/pollution.py
> +    TARGET_WIDTH = 100
Думаю константу лучше вынести из функции на уровень модуля (лишний байткод объявления переменной в функции), либо вынести как параметр функции

2023-04-19 21:12 UTC, Raidzin commented on src/bot/service/pollution.py
> +    coefficient = width / 100
Что за магическое число 100?

2023-04-21 10:35 UTC, ani-zia requested changes
Для работы над заявкой по свалке в лесу/борщевику/загрязнению водоёма важно, чтобы на фотографии можно было более менее что-то разглядеть.
Сейчас фотографии могут получится слишком маленькими, больше похожими на аватарки https://tracker.yandex.ru/POLLUTION-83 vs https://tracker.yandex.ru/POLLUTION-60

Сделаем такое дополнение к твоей задаче: 
* если полученный файл весит меньше 300КБ, то оставляем его как есть (вдруг кто-то небольшую картинку пришлет по какой-то причине, не будем делать ее еще меньше)
* если полученный файл весит больше 300КБ, уменьшаем его до ≈300КБ
* 300КБ тоже уносим в константы.

2023-04-21 10:35 UTC, ani-zia commented on .env.example
@Raidzin прав, без .env.example нельзя, верни пожалуйста его полностью :)

2023-04-21 10:35 UTC, ani-zia commented on src/bot/service/pollution.py
> +    TARGET_WIDTH = 100
@CodeDemonTony Константы храним в файле src/bot/const.py, можно туда вынести

2023-04-24 21:36 UTC, ani-zia requested changes
Из-за смеренного в develop PR с celery появились конфликты, надо поправить локально и в новом коммите закинуть)

2023-04-24 21:36 UTC, ani-zia commented on src/bot/service/pollution.py
> +    target_width = 1000
все цифры можно опять в константы унести, типа target_width=1000 и качество 95

2023-04-29 11:02 UTC, ani-zia requested changes
@CodeDemonTony тут осталось устранить конфликты

2023-05-02 15:51 UTC, Raidzin commented on src/bot/handlers/pollution.py
>          file_path = f"media\\{date}.jpg"
Пути до файлов нельзя хардкодить. Рекомендую использовать `pathlib.Path`
В данном случае `Path.cwd() / "media" / "{date}.jpg"`

2023-05-02 15:57 UTC, Raidzin commented on src/bot/handlers/pollution.py
>          date = datetime.now().strftime("%d_%m_%Y_%H_%M_%S")
Не лучший выбор для имени файла. А если два запроса в одну и ту же секунду? Один из файлов потеряется.
Лучше для названия использовать что-то более надёжно гарантирующее, что имена не пересекутся. Например есть такая интересная штука как UUID, а в питоне есть встроенный модуль для работы с uuid

2023-05-11 16:29 UTC, closed without merging