Feature/volunteer holiday
Studio-Yandex-Practicum/bot_delo_zhivet pull request #144
Opened 2023-05-17 05:06 UTC by Okslen

Задача https://www.notion.so/1-6a51ed8ad3434348b88aa4f859ee7713?pvs=4
Добавлены атрибуты holiday_start, holiday_end, in_active.
Проведены и пофиксены мигграции.

2023-05-17 14:42 UTC, ani-zia requested changes
Привет! 
Всё очень круто, спасибо! 
Давай добавим в админке переводы новых полей у Волонтера, для консистентности:
<img width="637" alt="Снимок экрана 2023-05-17 в 17 40 51" src="https://github.com/Studio-Yandex-Practicum/bot_delo_zhivet/assets/89511114/0139c338-b238-43ed-87cb-9024019ccb53">

Они в файле `admin/locales.py` собраны

2023-05-18 03:31 UTC, Okslen commented
Готово, добавил перевод в locales.py

2023-05-19 19:35 UTC, ani-zia approved these changes

2023-05-19 19:58 UTC, Raidzin approved these changes

2023-05-20 11:31 UTC, merged