add structlog
Studio-Yandex-Practicum/bot_delo_zhivet pull request #147
Opened 2023-05-26 17:58 UTC by Reiter83

Настроил structlog, добавил contexvars. Ссылка на задание в notion [https://www.notion.so/structlog-1-b2db289c392841ddbe3ff4cdda563791?pvs=4](url)

2023-05-29 15:29 UTC, Raidzin requested changes

2023-05-29 15:29 UTC, Raidzin commented on src/bot/handlers/loggers.py
Тут нужно совсем избавиться от `DualWriter` и вообще убрать параметр `logger_factory` по моему он по умолчанию будет в stdout писать. Но нужно перепроверить в [документации](https://www.structlog.org/en/stable/index.html)

З.Ы. Нужно не комментить код, а смело удалять. Если понадобится найдём в гите, там не потеряется)

2023-05-29 15:29 UTC, Raidzin commented on src/bot/application.py
Нужно почитать в [доках](https://www.structlog.org/en/stable/contextvars.html) как работают контекстные переменные и использовать их правильно!

2023-05-29 15:29 UTC, Raidzin commented on src/bot/application.py
> +    contextvars.bind_contextvars(app_url=str(uuid4()))
Не очень понятное название для контекстной переменной почему url это id?

2023-05-29 15:29 UTC, Raidzin commented on src/bot/application.py
> +    aps_logger.info("Webhook is. Application url: ", app_url=url)
Смысл контекстной переменной чтобы её один раз где-то _забиндить_ а потом не укаывать, она сама подтянется из контекста

2023-05-29 15:29 UTC, Raidzin commented on src/bot/application.py
> +            aps_logger.error("Got a JSONDecodeError ", json_error=error)
этого логгера (тут и во всех жругих местах) нужно подменить нашим `structlog`овым

2023-05-29 15:29 UTC, Raidzin commented on src/core/db/repository/abstract_repository.py
Тут всё то же что и с `application.py`

2023-06-02 16:08 UTC, Reiter83 commented
Убран logger factory, удалено объявление класса DualWriter, (в документации сказано, что по дефолту structlog пишет в stdout)
Во всех файлах импортирован логгер из loggers.py, вместо конструкции "logger = structlog.get_logger(...)"

В вызов лога теперь передаётся только событие, контекстварсы подтягиваются, но реализовано это через конструкцию "with bound_contextvars():" (как в документации), чтобы логгер не вставлял переменные в другие события на глобальном уровне

2023-06-04 20:05 UTC, ani-zia requested changes

2023-06-04 20:05 UTC, ani-zia commented on src/bot/application.py
> +from typing import List
у нас в зависимостях Python 3.10+, так что тайпинг должен работать без импорта List)

`If you use Python 3.9 or above, you don't have to import List from typing, you can use the same regular list type instead.`
отсюда https://fastapi.tiangolo.com/it/python-types/

2023-06-05 20:39 UTC, Raidzin requested changes
Всё хорошо, только нужно убрать контекстный менеджер для логгирования параметров

2023-06-05 20:39 UTC, Raidzin commented on src/bot/application.py
> +        logger.info("Webhook initialized")
А лучше просто 

```python
logger.info("webhook initialized", app_url=url)
```

(И так относится ко всем подобным вызовам)

2023-06-06 16:48 UTC, Reiter83 commented
Убрал контекстный менеджер и заменил конструкцию logger'a

2023-06-09 15:39 UTC, Raidzin approved these changes

2023-06-09 18:37 UTC, ani-zia requested changes
@Reiter83 все отлично, но надо порешать конфликт на файле application и тогда смогу забрать-смержить всё)

2023-06-09 18:59 UTC, Reiter83 commented
@ani-zia Готово, исправил конфликт.

2023-06-09 19:19 UTC, ani-zia approved these changes

2023-06-09 19:19 UTC, merged