Feature/env files split
Studio-Yandex-Practicum/bot_delo_zhivet pull request #151
Opened 2023-06-03 19:39 UTC by onemi

[Задача](https://www.notion.so/env-1-db1507a1e1194becbe7bdfcf45bf7564?pvs=4) разбить старый .env файл на отдельные файлы по микросервисам/контейнерам:

- Добавила заготовки для всех .env.X.example с константами
- Добавила небольшие правки в docker-compose файлы для авто-переключения между локальной ДБ и сборкой бота в Docker
- Сделали правки в коде, где используются значения из .env переменных/загружаются .env файлы
- Добавила опциональный фикс в Dockerfile, если у кого-то также как и у меня проблемы с запуском Poetry в контейнере в runtime
- Добавила комментарии в delo-local.conf (тестировала одновременно с тем, как был смержен Машин PR c добавлением flask admin в контейнер)
- Обновила и исправила README
- В файлах, где что-то делала по .env, исправила форматирование в соответствии с PEP

2023-06-05 16:50 UTC, ani-zia approved these changes
проверила, все работает, супер)

2023-06-06 19:48 UTC, ani-zia requested changes
@Raidzin предложил хорошую правку: т.к. `env`-файлов много теперь, давай уберем их в папку `infrastructure` ?

2023-06-09 10:43 UTC, Raidzin approved these changes

2023-06-09 10:43 UTC, Raidzin commented on .dockerignore
> +.env*.example
Хорошее дополнение!

2023-06-09 10:43 UTC, Raidzin commented on .gitignore
> +!.env*.example
👍

2023-06-09 10:46 UTC, ani-zia approved these changes
все отлично, спасибо)

2023-06-09 10:46 UTC, merged