Feature/refactoring tag names
Studio-Yandex-Practicum/bot_delo_zhivet pull request #153
Opened 2023-06-14 08:06 UTC by margoloko

https://www.notion.so/2-ca997e7327654527ad98d475ecfb2282?pvs=4
Добавила заглавную букву на вывод в бот тегам. Использовала библиотеку python-Levenshtein для проверки уникальности тегов, при добавлении в админке, тонко настроить не вышло, но помогает исключить добавления тегов с опечатками и разных case

2023-06-14 20:00 UTC, Raidzin reviewed
В целом всё вроде хорошо. Можно одно место переписать в более _питонячем_ стиле. Полезно для практики и работать будет чуть быстрее!)

2023-06-16 15:35 UTC, Raidzin approved these changes

2023-06-16 15:48 UTC, ani-zia requested changes
@margoloko спасибо тебе, все супер и работает идеально, от Леши тоже ок.

Надо только порешать конфликты (они из-за мержа предыдущего PR с логами)) и тогда этот тоже сможем смержить :)

2023-06-17 13:44 UTC, ani-zia approved these changes

2023-06-17 13:44 UTC, merged