all but tracker
Studio-Yandex-Practicum/bot_delo_zhivet pull request #162
Opened 2023-07-08 09:15 UTC by mashkay

добавлена кнопка Уйти в отпуск/Выйти из отпуска
оно пишет в базу, но меняет статус в трекере 

изменения в статуса в трекере пока не получились 
- Поля [status] только для чтения.

2023-07-19 21:32 UTC, Raidzin requested changes
В целом всё супер! Но есть некоторые улучшения в плане readability.

```
...
Readability counts.
...
```

2023-07-19 21:32 UTC, Raidzin commented on src/bot/handlers/holiday.py
> +async def endless_holiday_now_save(update: Update, context: ContextTypes.DEFAULT_TYPE) -> str:
Название звучит прикольно, но не супер понятно (почему тут `now`?)

2023-07-19 21:32 UTC, Raidzin commented on src/bot/handlers/holiday.py
> +async def stop_holiday_today_save(update: Update, context: ContextTypes.DEFAULT_TYPE) -> str:
Тут уже хорошо (но почему тут теперь `today`?)

2023-07-19 21:32 UTC, Raidzin commented on src/bot/handlers/state_constants.py
> +HOLIDAY_STOP_NOW = "HOLIDAY_STOP_NOW"
А вот здесь уже `stop_NOW`!

_консистентность matters_

2023-07-19 21:32 UTC, Raidzin commented on src/bot/service/holiday.py
> +def get_volunteer_is_in_vocation(volunteer: Volunteer) -> bool:
Почему тут `vocation`, функция вроде про `holiday` O_o

2023-07-19 21:32 UTC, Raidzin commented on src/bot/service/volunteer.py
> +        if data[HOLIDAY_START] is not None:
может просто `and`?
(вопрос с подвохом)

2023-07-21 04:51 UTC, mashkay commented on src/bot/handlers/holiday.py
> +async def endless_holiday_now_save(update: Update, context: ContextTypes.DEFAULT_TYPE) -> str:
now потому что если мы будем делать управление датами отпуска то может появиться функа endless_holiday_from_date_save или типа того, с уходом в бесконечный отпуск с даты

2023-07-21 06:38 UTC, mashkay commented
убрала баг с конфликтом : - Задача: не удалось сохранить изменения, попробуйте ещё раз
оказывается после  trasiation execute надо обновить issue что бы можно было делать его update

маленькие изменения в названиях

2023-07-24 10:28 UTC, merged