Feature/dadata unavaliability handling
Studio-Yandex-Practicum/bot_delo_zhivet pull request #165
Opened 2023-07-20 14:10 UTC by epanchincev

Задача в Notion - https://www.notion.so/DaData-870d8cbf96f84a0999ce847ad92278d3

- [ ] Заметил что в проекте, при использовании асинхронного фреймворка, использовался синхронный запрос в дадату. - Исправил. bot.service.dadata
- [ ] Теперь обрабатывается исключение библиотеки http и выбрасывается собственное выключение bot.exceptions, bot.service.dadata
- [ ] В коде, при обработке адреса в файле bot.service.common_functions не соблюдался принцип dry, и бесмысленно каждый раз создавались статичные клавиатуры. Вынес клавиатуры касающиеся обработки адреса в bot.keyboards. Отрефакторил код. Теперь обработка адреса, это отдельная функция вызывающаяся в двух хендлерах.  В соответствии с заданием, появился хендлер отрабатывающий кнопку повторной отправки, в случае отсутствия соединения с сервисом dadata
- [ ] Добавил structlog в функцию запроса данных с dadata

2023-07-20 17:56 UTC, Raidzin requested changes
Асинхронная дадата 🔥. Есть несколько рекомендация по readability

```python
...
Readability counts.
...
```

2023-07-20 17:56 UTC, Raidzin commented on src/bot/keyboards.py
> +BACK_KB = InlineKeyboardMarkup(
В данном контексте суффикс KB понятен, но в другом, скорее всего нет. Его лучше убрать

А в коде делать как-то так:

```python
from ... import keyboards

foo = keyboards.BACK
```

2023-07-20 17:56 UTC, Raidzin commented on src/bot/service/dadata.py
> +            return None
Лучше не выдавать нон, а перекидывать исключение

2023-07-20 17:56 UTC, Raidzin commented on src/bot/service/common_functions.py
> +        if address is not None:
Если кидать исключение, а не Ноне то можно будет не делать проверку на Ноне и отлавливать вариант во втором блоке `except`

2023-07-21 10:13 UTC, epanchincev commented
Все по существу, спасибо! Сделал изменения согласно ревью. Так же добавил обработку исключения по 403.

2023-07-31 11:33 UTC, Raidzin approved these changes

2023-07-31 11:34 UTC, merged