edit tags
Studio-Yandex-Practicum/bot_delo_zhivet pull request #166
Opened 2023-07-26 20:09 UTC by mashkay

[Notion ](https://www.notion.so/e74f4cba96fe42c8add5596a4b13cd36?p=caaf34cae1e7422c9a3159d479981d98&pm=s)

### в src.api новый файл tags_update.py
в нем Класс для обновления тегов события в трекере
получилось сделать bulkupdate для issues 
сделала проверку что нет задач с тегом и удаление тега
2 корутины для тасков селери : 
* для изменения имени тега в задачах + удаление тега  из очереди если с ним нет тасков
* для удаления тега из задач+ удаление тега из очереди если с ним нет тасков

### в src.bot.tasks 4 новых таска
* удаление из задач + удаление из очереди Х2 (для Pollution и для assistance_disabled)
* изменение  в задачах + удаление из очереди Х2 (для Pollution и для assistance_disabled)

### в admin.views
* сделала AbstractTagModelView и от него наследовала TagAssistanceModelView и TagPollutionModelView
* в нем переопределены методы :
      * on_model_change (вызов метода проверки уникальности остался) 
      *  after_model_change
      *  on_model_delete
      *  after_model_delete
      
* мне не очень нравится что пришлось в класс запоминать старое состояние базы до изменения, а именно 
      * старое имя и id тега
      * при удалении список ticketID задач в которых стоял тег
      у меня не получилось по-другому эти данные добыть в состоянии after_model_change и after_model_delete
      
### почистила относительные импорты

2023-07-27 19:43 UTC, Raidzin requested changes
Хорошее начало. Доделки

2023-07-27 19:43 UTC, Raidzin commented on admin/views.py
> +        """Этот метод должен быть переопределен в наследниках"""
~~можно~~ нужно это явно указать в коде. `abc` в помощь

2023-07-27 19:43 UTC, Raidzin commented on admin/views.py
> +    """Абстрактный класс для наследования вью-классов тегов"""
~~можно~~ нужно это явно указать в коде. `abc` в помощь

2023-07-29 07:41 UTC, mashkay commented on admin/views.py
> +        """Этот метод должен быть переопределен в наследниках"""
не получается с abc покопалась там у flask-admin уже используются в глубине мета классы и идет наследование не от самого класса а от объекта  и в итоге лезет 
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
декоратор  
```
@abstractmethod
```
без использования мета класса бесполезен ( 

я это место ровно из flask-admin списала они у себя тоже используют 
```
raise NotImplementedError()
```
видимо по той же причине

2023-08-03 16:06 UTC, Raidzin submitted a review, later dismissed

2023-08-03 16:11 UTC, Raidzin approved these changes

2023-08-03 16:12 UTC, merged