refactoring logs
Studio-Yandex-Practicum/bot_delo_zhivet pull request #169
Opened 2023-07-28 17:32 UTC by YourHoliness

Добавлены логи в админку
Добавлено несколько логов в структуру бота.
Не придумал как ограничить вывод однотипных сообщений в логах.
По большей части это логи уровня DEBUG, их можно скрыть, указав в конфиге уровень логирования.
Есть еще места, в которых можно прикрутить и модифицировать логирование, но нужно мнение остальных. Пока не особо представляю, что еще критичного можно сунуть в логирование.

2023-07-31 12:18 UTC, Raidzin requested changes
Есть маленькие правки + нужно решить конфликты

2023-07-31 12:18 UTC, Raidzin commented on admin/utils.py
> +        distance_score = distance(tag.name.lower(), model.name.lower())
Вот тут можно использовать новый оператор `:=`
работает так
```python
...
if foo := spam() < eggs:
    logger(... foo=foo)
    ...
```

2023-07-31 12:52 UTC, YourHoliness commented on admin/utils.py
> +        distance_score = distance(tag.name.lower(), model.name.lower())
Done~

2023-08-03 16:02 UTC, Raidzin approved these changes

2023-08-03 16:02 UTC, merged